# Generated by Django 5.1.5 on 2026-05-20 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscard',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='businesscard',
            name='website',
        ),
        migrations.AddField(
            model_name='businesscard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/'),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
