# Generated by Django 5.1.5 on 2026-05-25 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_alter_businesscard_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('contact', 'Contact'), ('company', 'Company'), ('event', 'Event')], max_length=50)),
                ('source_id', models.PositiveIntegerField()),
                ('display_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type'], name='scanner_kno_entity__0a31c8_idx'), models.Index(fields=['source_id'], name='scanner_kno_source__603194_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'source_id'), name='unique_knowledge_entity')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('WORKS_AT', 'Works At'), ('MET_AT', 'Met At')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='scanner.knowledgeentity')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='scanner.knowledgeentity')),
            ],
            options={
                'indexes': [models.Index(fields=['relationship_type'], name='scanner_kno_relatio_9a2ce8_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_entity', 'relationship_type', 'target_entity'), name='unique_knowledge_relationship')],
            },
        ),
    ]
