# Generated by Django 5.1.5 on 2026-05-25 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_knowledgeentity_knowledgerelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('chunk_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('contact', 'Contact'), ('company', 'Company'), ('event', 'Event')], max_length=50)),
                ('entity_id', models.PositiveIntegerField()),
                ('text_content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('index_status', models.CharField(choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('stale', 'Stale'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddingIndexMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_id', models.CharField(db_index=True, max_length=255)),
                ('embedding_model', models.CharField(max_length=255)),
                ('index_backend', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_map', to='scanner.documentchunk')),
            ],
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='scanner.knowledgedocument'),
        ),
    ]
