# Generated by Django 5.1.5 on 2026-05-25 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_documentchunk_knowledgedocument_embeddingindexmap_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeentity',
            name='entity_type',
            field=models.CharField(choices=[('contact', 'Contact'), ('company', 'Company'), ('event', 'Event'), ('domain', 'Domain')], max_length=50),
        ),
        migrations.AlterField(
            model_name='knowledgerelationship',
            name='relationship_type',
            field=models.CharField(choices=[('WORKS_AT', 'Works At'), ('MET_AT', 'Met At'), ('BELONGS_TO_DOMAIN', 'Belongs To Domain')], max_length=100),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='businesscard',
            name='domains',
            field=models.ManyToManyField(blank=True, to='scanner.domain'),
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('pitching', 'Pitching'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='lead', max_length=50)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='scanner.businesscard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
