# Generated by Django 5.1.5 on 2026-05-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_alter_knowledgeentity_entity_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='knowledgerelationship',
            name='scanner_kno_relatio_9a2ce8_idx',
        ),
        migrations.AlterField(
            model_name='knowledgeentity',
            name='entity_type',
            field=models.CharField(choices=[('contact', 'Contact'), ('company', 'Company'), ('event', 'Event'), ('domain', 'Domain'), ('opportunity', 'Opportunity')], max_length=50),
        ),
        migrations.AlterField(
            model_name='knowledgerelationship',
            name='relationship_type',
            field=models.CharField(choices=[('WORKS_AT', 'Works At'), ('MET_AT', 'Met At'), ('BELONGS_TO_DOMAIN', 'Belongs To Domain'), ('LINKED_TO_OPPORTUNITY', 'Linked To Opportunity')], max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
