# Generated by Django 5.1.5 on 2026-05-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0011_alter_businesscard_first_name_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
