# Generated by Django 5.1.5 on 2026-05-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_alter_businesscard_website_alter_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeentity',
            name='custom_tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='knowledgeentity',
            name='priority_score',
            field=models.IntegerField(default=0),
        ),
    ]
