# Generated by Django 5.1.5 on 2026-05-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_knowledgeentity_custom_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='value',
        ),
    ]
