# Generated by Django 5.1.5 on 2026-06-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0017_billingprofile_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_content', models.CharField(max_length=255)),
                ('ad_file', models.FileField(upload_to='ads/')),
                ('placement', models.CharField(choices=[('dashboard_top', 'Dashboard Top Banner'), ('sidebar_right', 'Sidebar Advertisement'), ('email_blast', 'Email Newsletter Spot'), ('login_page', 'Login Page Feature')], max_length=50)),
                ('strategy', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('running_time', models.TimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('avg_duration', models.FloatField(default=0.0)),
                ('last_event', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='canceled_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
